### ISSUE TITLE
Lancement par le launcher rend sniffer inutilisable

### ISSUE THREAD

**Issue by Faareoh** [RBlanchet/D2.Sniffer#1]
Salut, je ne sais pas trop si le projet est encore actif, mais depuis quelques mois le client DOFUS passe par le launcher pour se connecter, le sniffer n'est donc plus fonctionnel vu que le process est lancé via le .exe

Est-il prévu un jour d'adapter ça ?

**Comment by RBlanchet** [comment]
Hello, en effet depuis quelques temps le lancement via le Launcher pose beaucoup de problèmes dans le monde de l'émulation, j'avoue ne pas avoir eu de temps de l'adapter actuellement ... Peut-être un jour mais pas dans l'immédiat, désolé ... Tu peux néanmoins essayer de fork le repo et d'adapter ta solution à ce projet
